version: "2"
services:
  product-review:
    build:
      context: ./product_review/
      dockerfile: Dockerfile
    image: product-review
    container_name: product-review
    ports:
      - "8081:8081"
  product-service:
    build:
      context: ./product_service/
      dockerfile: Dockerfile
    image: product-service
    container_name: product-service
    ports:
      - "8080:8080"
    environment:
      - REVIEW_SERVICE_URL=http://product-review-service:8081
    deploy:
      replicas: 4
      update_config:
        parallelism: 2
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health || exit 1"]